# Generated by Django 4.2.30 on 2026-06-16 16:37

import apps.shared.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributionDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_attribution', models.FloatField(default=0.0)),
                ('niveau_priorite', models.CharField(choices=[('urgent', 'Urgent'), ('eleve', 'Élevé'), ('normal', 'Normal'), ('faible', 'Faible')], default='normal', max_length=20)),
                ('source_attribution', models.CharField(choices=[('auto', 'Automatique'), ('ia', 'Intelligence Artificielle'), ('manuel', 'Manuel'), ('reattribution', 'Réattribution'), ('superviseur', 'Superviseur')], default='auto', max_length=20)),
                ('justification_ia', models.TextField(blank=True, null=True)),
                ('date_attribution', models.DateTimeField(auto_now_add=True)),
                ('date_limite_traitement', models.DateTimeField()),
                ('notification_24h_envoyee', models.BooleanField(default=False)),
                ('notification_48h_envoyee', models.BooleanField(default=False)),
                ('est_reattribution', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Attribution de Dossier',
                'verbose_name_plural': 'Attributions de Dossiers',
                'db_table': 'attribution_dossier',
            },
        ),
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('nationalite', models.CharField(default='Sénégalaise', max_length=50, verbose_name='Nationalité')),
                ('nom_pere', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom complet du père')),
                ('nom_mere', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom complet de la mère')),
                ('telephone', models.CharField(max_length=20, validators=[apps.shared.validators.validate_phone_senegal], verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('quartier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quartier')),
                ('numero_cni', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[apps.shared.validators.validate_cni], verbose_name='Numéro CNI')),
                ('numero_passeport', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de passeport')),
                ('date_expiration_cni', models.DateField(blank=True, null=True, verbose_name="Date d'expiration CNI")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
            ],
            options={
                'verbose_name': 'Citoyen',
                'verbose_name_plural': 'Citoyens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_action', models.CharField(max_length=255)),
                ('dossier_id', models.CharField(max_length=100)),
                ('agent_avant', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_apres', models.CharField(blank=True, max_length=255, null=True)),
                ('score_calcule', models.FloatField(default=0.0)),
                ('justification', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Journal Attribution',
                'verbose_name_plural': 'Journaux Attributions',
                'db_table': 'attribution_journal',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProfilAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialites', models.JSONField(default=list)),
                ('disponibilite', models.BooleanField(default=True)),
                ('charge_maximale', models.PositiveIntegerField(default=10)),
                ('score_global', models.FloatField(default=0.0)),
                ('temps_moyen_traitement', models.FloatField(default=0.0)),
                ('taux_reussite', models.FloatField(default=0.0)),
                ('taux_respect_delais', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil Agent',
                'verbose_name_plural': 'Profils Agents',
                'db_table': 'attribution_profil_agent',
            },
        ),
    ]
