# Generated by Django 4.2.30 on 2026-06-16 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etat_civil', '0001_initial'),
        ('communes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dossiers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilagent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalattribution',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_journal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citoyens_guichet', to='communes.commune', verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citoyens_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='attributiondossier',
            name='agent_actuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions_actuelles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attributiondossier',
            name='ancien_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anciennes_attributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attributiondossier',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='dossiers.dossier'),
        ),
        migrations.AddField(
            model_name='attributiondossier',
            name='responsable_attribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions_effectuees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='citoyen',
            index=models.Index(fields=['numero_cni'], name='etat_civil__numero__a32778_idx'),
        ),
        migrations.AddIndex(
            model_name='citoyen',
            index=models.Index(fields=['telephone'], name='etat_civil__telepho_264d32_idx'),
        ),
        migrations.AddIndex(
            model_name='citoyen',
            index=models.Index(fields=['nom', 'prenom'], name='etat_civil__nom_0c65ed_idx'),
        ),
    ]
