# Generated by Django 4.2.30 on 2026-06-16 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='FCM Token')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name="Type d'appareil")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Alerte'), ('error', 'Erreur'), ('update', 'Mise à jour')], default='info', max_length=20, verbose_name='Type de notification')),
                ('channel', models.CharField(choices=[('internal', 'Interne'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], default='internal', max_length=20, verbose_name='Canal')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Métadonnées JSON utiles pour la notification.', verbose_name='Données associées')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
