# Generated by Django 4.2.30 on 2026-06-16 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('category', models.CharField(choices=[('road', 'Voirie'), ('lighting', 'Éclairage public'), ('waste', 'Déchets / Salubrité'), ('water', 'Eau / Assainissement'), ('security', 'Sécurité'), ('other', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('received', 'Reçu'), ('in_progress', 'En traitement'), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='received', max_length=20, verbose_name='Statut')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/photos/', verbose_name='Photo')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Notes administration')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('starts_at', models.DateTimeField(verbose_name='Date de début')),
                ('ends_at', models.DateTimeField(verbose_name='Date de fin')),
            ],
            options={
                'verbose_name': 'Sondage',
                'verbose_name_plural': 'Sondages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, verbose_name="Texte de l'option")),
                ('votes_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de votes')),
            ],
            options={
                'verbose_name': 'Option de sondage',
                'verbose_name_plural': 'Options de sondage',
            },
        ),
        migrations.CreateModel(
            name='SurveyVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence transaction')),
                ('provider', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('free_money', 'Free Money')], max_length=20, verbose_name='Opérateur')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (FCFA)')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('external_transaction_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID transaction opérateur')),
                ('receipt_url', models.URLField(blank=True, default='', verbose_name='URL reçu PDF')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
