# Generated by Django 4.2.30 on 2026-06-16 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('communes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dossiers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Citoyen'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='dossiers.dossier', verbose_name='Dossier'),
        ),
        migrations.AddField(
            model_name='surveyvote',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_votes', to=settings.AUTH_USER_MODEL, verbose_name='Citoyen'),
        ),
        migrations.AddField(
            model_name='surveyvote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_records', to='services.surveyoption', verbose_name='Option'),
        ),
        migrations.AddField(
            model_name='surveyvote',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='services.survey', verbose_name='Sondage'),
        ),
        migrations.AddField(
            model_name='surveyoption',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='services.survey', verbose_name='Sondage'),
        ),
        migrations.AddField(
            model_name='survey',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='communes.commune', verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='survey',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='report',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Citoyen'),
        ),
        migrations.AddField(
            model_name='report',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='communes.commune', verbose_name='Commune'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference'], name='services_tr_referen_f306f9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['citizen'], name='services_tr_citizen_d78ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='services_tr_status_b8e220_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['provider'], name='services_tr_provide_4884c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyvote',
            unique_together={('survey', 'citizen')},
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['category'], name='services_re_categor_28bba6_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='services_re_status_6fa29b_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['commune'], name='services_re_commune_25a67f_idx'),
        ),
    ]
