# Generated by Django 4.2.30 on 2026-06-16 16:37

import apps.shared.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communes', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[apps.shared.validators.validate_phone_senegal], verbose_name='Téléphone')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('role', models.CharField(choices=[('citizen', 'Citoyen'), ('agent', 'Agent'), ('civil_admin', 'Administrateur de mairie'), ('civil_admin_supervisor', 'Administrateur général de mairie'), ('super_admin', 'Super administrateur')], db_index=True, default='citizen', max_length=25, verbose_name='Rôle')),
                ('agent_capabilities', models.JSONField(blank=True, default=list, help_text="Liste des étapes pour lesquelles cet agent est habilité (ex: ['reception', 'verification'])", verbose_name="Capacités de l'agent")),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Avatar')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='Doit changer de mot de passe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='communes.commune', verbose_name='Commune')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(help_text='Le numéro de téléphone ou email à vérifier', max_length=100, verbose_name='Identifiant (Email ou Téléphone)')),
                ('code', models.CharField(max_length=6, verbose_name='Code OTP')),
                ('is_used', models.BooleanField(default=False, verbose_name='Est utilisé')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Code OTP',
                'verbose_name_plural': 'Codes OTP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['identifier', 'code'], name='users_otpco_identif_4528d2_idx'), models.Index(fields=['is_used'], name='users_otpco_is_used_fa06ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure de connexion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de connexion',
                'verbose_name_plural': 'Historiques de connexion',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, default='', verbose_name='Adresse')),
                ('cni_number', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[apps.shared.validators.validate_cni], verbose_name='Numéro CNI')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('place_of_birth', models.CharField(blank=True, default='', max_length=100, verbose_name='Lieu de naissance')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], default='', max_length=1, verbose_name='Genre')),
                ('profession', models.CharField(blank=True, default='', max_length=100, verbose_name='Profession')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/photos/', verbose_name='Photo')),
                ('cni_document', models.FileField(blank=True, null=True, upload_to='profiles/cni/', verbose_name='Document CNI (Recto/Verso)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil citoyen',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['commune'], name='users_user_commune_9042d0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_user_is_acti_ddda02_idx'),
        ),
    ]
