# Generated by Django 4.2.30 on 2026-06-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='break_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Début de pause'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_dispatch_eligible',
            field=models.BooleanField(default=True, verbose_name='Éligible au dispatch'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_on_break',
            field=models.BooleanField(default=False, verbose_name='En pause'),
        ),
    ]
