# Generated by Django 4.2.30 on 2026-06-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_break_started_at_user_is_dispatch_eligible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citoyen'), ('agent', 'Agent'), ('civil_admin', 'Administrateur de mairie'), ('civil_admin_supervisor', 'Administrateur général de mairie'), ('super_admin', 'Super administrateur'), ('MAIRE', 'Maire')], db_index=True, default='citizen', max_length=25, verbose_name='Rôle'),
        ),
    ]
