# Generated by Django 4.2.30 on 2026-06-16 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('region', models.CharField(db_index=True, max_length=100, verbose_name='Région')),
                ('department', models.CharField(max_length=100, verbose_name='Département')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code administratif')),
                ('address', models.TextField(blank=True, default='', verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('nom_commune_officiel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom officiel de la commune')),
                ('devise', models.CharField(default='Un Peuple - Un But - Une Foi', max_length=255, verbose_name='Devise')),
                ('nom_officier_etat_civil', models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'officier d'état civil")),
                ('chemin_cachet_communal', models.CharField(blank=True, max_length=500, null=True, verbose_name='Chemin du cachet communal')),
                ('chemin_cachet_nominal', models.CharField(blank=True, max_length=500, null=True, verbose_name='Chemin du cachet nominal')),
                ('chemin_signature_officier', models.CharField(blank=True, max_length=500, null=True, verbose_name="Chemin de la signature de l'officier")),
                ('prefixe_residence', models.CharField(default='RES-2026-', max_length=20, verbose_name='Préfixe Résidence')),
                ('prefixe_mariage', models.CharField(default='MAR-2026-', max_length=20, verbose_name='Préfixe Mariage')),
                ('prefixe_deces', models.CharField(default='DEC-2026-', max_length=20, verbose_name='Préfixe Décès')),
                ('numero_registre_courant', models.IntegerField(default=1, verbose_name='Numéro de registre courant')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='communes_co_name_9b0e58_idx'), models.Index(fields=['region'], name='communes_co_region_305a1e_idx'), models.Index(fields=['code'], name='communes_co_code_1f2d96_idx')],
            },
        ),
    ]
