# Generated by Django 4.2.30 on 2026-06-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(blank=True, max_length=300)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('horaires', models.TextField(blank=True)),
                ('est_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mairies', to='communes.commune')),
            ],
            options={
                'verbose_name': 'Mairie',
                'verbose_name_plural': 'Mairies',
                'ordering': ['nom'],
            },
        ),
    ]
