# Generated by Django 4.2.30 on 2026-06-16 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('USER', 'Utilisateur'), ('SYSTEM', 'Système'), ('ANONYMOUS', 'Anonyme')], db_index=True, default='USER', max_length=20, verbose_name="Type d'utilisateur")),
                ('status', models.CharField(choices=[('SUCCESS', 'Succès'), ('FAILURE', 'Échec'), ('ERROR', 'Erreur')], db_index=True, default='SUCCESS', max_length=20, verbose_name='Statut')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('STATUS_CHANGE', 'Changement de statut'), ('ROLE_CHANGE', 'Changement de rôle'), ('UPLOAD', 'Téléversement'), ('DOWNLOAD', 'Téléchargement'), ('ACCESS_DENIED', 'Accès refusé')], db_index=True, max_length=20, verbose_name='Action')),
                ('resource_type', models.CharField(db_index=True, max_length=50, verbose_name='Type de ressource')),
                ('resource_id', models.UUIDField(blank=True, null=True, verbose_name='ID ressource')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-created_at'],
            },
        ),
    ]
