# Generated by Django 4.2.7 on 2026-06-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ndiogoyechatlog",
            name="feedback_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ndiogoyechatlog",
            name="rating",
            field=models.IntegerField(
                blank=True, help_text="1 pour positif, -1 pour négatif", null=True
            ),
        ),
    ]
