# Generated by Django 4.2.30 on 2026-06-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
        ('ai', '0002_ndiogoyechatlog_feedback_comment_and_more'),
    ]

    operations = [
    ]
