# Generated by Django 4.2.30 on 2026-06-19 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_merge_20260616_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ndiogoyechatlog',
            name='user',
        ),
    ]
