# Generated by Django 4.2.30 on 2026-06-16 16:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Référence')),
                ('type', models.CharField(choices=[('birth_certificate', 'Acte de naissance'), ('marriage_certificate', 'Acte de mariage'), ('death_certificate', 'Acte de décès'), ('residence_certificate', 'Certificat de résidence'), ('regularisation', 'Demande de régularisation'), ('autorisation_construire', 'Autorisation de construire'), ('mutation_parcelle', 'Mutation de parcelle'), ('other', 'Autre')], db_index=True, max_length=30, verbose_name='Type de dossier')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('in_review', 'En cours de vérification'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('completed', 'Terminé')], db_index=True, default='draft', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées (Formulaire dynamique)')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Motif de rejet')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DossierComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('content', models.TextField(verbose_name='Contenu')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistreCivil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('numero_registre', models.CharField(max_length=50, verbose_name='Numéro de registre')),
                ('annee_registre', models.IntegerField(verbose_name='Année de registre')),
                ('type_acte', models.CharField(choices=[('birth_certificate', 'Acte de naissance'), ('marriage_certificate', 'Acte de mariage'), ('death_certificate', 'Acte de décès'), ('residence_certificate', 'Certificat de résidence'), ('regularisation', 'Demande de régularisation'), ('autorisation_construire', 'Autorisation de construire'), ('mutation_parcelle', 'Mutation de parcelle'), ('other', 'Autre')], max_length=30, verbose_name="Type d'acte")),
                ('nom_complet_personne', models.CharField(max_length=255, verbose_name='Nom complet sur le registre')),
                ('date_naissance_personne', models.DateField(verbose_name='Date de naissance sur le registre')),
                ('conjoint_nom_complet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom complet du conjoint')),
                ('nom_pere', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du père')),
                ('nom_mere', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la mère')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True, verbose_name='Sexe')),
                ('lieu_naissance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de naissance')),
                ('profession_pere', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profession du père')),
                ('profession_mere', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profession de la mère')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registres', to='communes.commune', verbose_name='Commune de déclaration')),
            ],
            options={
                'verbose_name': 'Registre Civil (Simulation)',
                'verbose_name_plural': 'Registres Civils (Simulation)',
                'ordering': ['-annee_registre', 'numero_registre'],
            },
        ),
    ]
