# Generated by Django 4.2.30 on 2026-06-16 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etat_civil', '0001_initial'),
        ('communes', '0001_initial'),
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiercomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_comments', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='dossiercomment',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dossiers.dossier', verbose_name='Dossier'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dossiers', to=settings.AUTH_USER_MODEL, verbose_name='Agent responsable'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='citizen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to=settings.AUTH_USER_MODEL, verbose_name='Citoyen'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='citoyen_guichet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='etat_civil.citoyen', verbose_name='Citoyen (Guichet)'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='communes.commune', verbose_name='Commune'),
        ),
        migrations.AlterUniqueTogether(
            name='registrecivil',
            unique_together={('numero_registre', 'annee_registre', 'commune', 'type_acte')},
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['reference'], name='dossiers_do_referen_ae94ef_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['type'], name='dossiers_do_type_35cd1c_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['status'], name='dossiers_do_status_f35af7_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['citizen'], name='dossiers_do_citizen_b3bd77_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['commune'], name='dossiers_do_commune_015106_idx'),
        ),
        migrations.AddIndex(
            model_name='dossier',
            index=models.Index(fields=['status', 'commune'], name='dossiers_do_status_00263b_idx'),
        ),
    ]
