# Generated by Django 4.2.30 on 2026-06-19 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dossiers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='agent_traitant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_traites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_decision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='date_soumission_maire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='decision_maire',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('EN_APPROBATION', 'Soumis au Maire'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20),
        ),
    ]
