# Generated by Django 4.2.30 on 2026-06-16 16:37

import apps.documents.models
import apps.shared.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path, validators=[apps.shared.validators.validate_document_file], verbose_name='Fichier')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nom original')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('scan', 'Scan')], max_length=10, verbose_name='Type de fichier')),
                ('file_size', models.IntegerField(verbose_name='Taille (bytes)')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('ocr_status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=15, verbose_name='Statut OCR')),
                ('ocr_text', models.TextField(blank=True, default='', verbose_name='Texte OCR')),
                ('sha256_hash', models.CharField(blank=True, default='', help_text='Empreinte SHA-256 du fichier uploadé (anti-doublon).', max_length=64, verbose_name='Hash SHA-256')),
                ('mime_type', models.CharField(blank=True, default='', help_text="Type MIME détecté lors de l'upload (ex: image/jpeg, application/pdf).", max_length=100, verbose_name='Type MIME')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedCertificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(upload_to=apps.documents.models.certificate_upload_path, verbose_name='Fichier PDF')),
                ('data_payload', models.TextField(help_text='ref|commune|nom|date_naissance|officier_id|pdf_sha256', verbose_name='Payload signé (données brutes)')),
                ('pdf_sha256', models.CharField(max_length=64, verbose_name='Hash SHA-256 du PDF')),
                ('hmac_signature', models.CharField(max_length=64, verbose_name='Signature HMAC-SHA256')),
                ('cachet_communal_svg', models.CharField(blank=True, default='', max_length=255, verbose_name='Chemin SVG cachet communal')),
                ('signature_officier_svg', models.CharField(blank=True, default='', max_length=255, verbose_name='Chemin SVG signature officier')),
            ],
            options={
                'verbose_name': 'Certificat Généré',
                'verbose_name_plural': 'Certificats Générés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimbreFiscal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=30, unique=True, verbose_name='Référence du timbre')),
                ('montant', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Montant (FCFA)')),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
            ],
            options={
                'verbose_name': 'Timbre Fiscal',
                'verbose_name_plural': 'Timbres Fiscaux',
                'ordering': ['-created_at'],
            },
        ),
    ]
