# Generated by Django 4.2.30 on 2026-06-16 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcertificate',
            name='dossier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='dossiers.dossier', verbose_name='Dossier'),
        ),
    ]
