# Generated by Django 4.2.30 on 2026-06-16 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcertificate',
            name='officier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Officier signataire'),
        ),
        migrations.AddField(
            model_name='generatedcertificate',
            name='timbre',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate', to='documents.timbrefiscal', verbose_name='Timbre fiscal'),
        ),
        migrations.AddField(
            model_name='document',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dossiers.dossier', verbose_name='Dossier'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Téléversé par'),
        ),
        migrations.AddIndex(
            model_name='generatedcertificate',
            index=models.Index(fields=['dossier'], name='documents_g_dossier_4544e0_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcertificate',
            index=models.Index(fields=['hmac_signature'], name='documents_g_hmac_si_9adc04_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['dossier'], name='documents_d_dossier_f64792_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by'], name='documents_d_uploade_6455fb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['ocr_status'], name='documents_d_ocr_sta_9ac6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['sha256_hash'], name='documents_d_sha256__1b7de8_idx'),
        ),
    ]
